---
-
  hosts: nginx1_server
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/BoodskapPlatform/boodskap-ui.git'
        clone: yes
        accept_newhostkey: yes
        dest: /home/boodskapui/webapps/boodskap-ui
        version: v5.0
        force: yes
        single_branch: yes
      register: gitoutput

    - debug: msg="{{ gitoutput }}"
    
    - 
      name: Branch status.
      command: git branch
      args:
        chdir: /home/boodskapui/webapps/boodskap-ui
      register: branch_output

    - debug: msg="{{ branch_output }}"

    - 
      name: This command will install dependencies.
      command: npm install
      args:
        chdir: /home/boodskapui/webapps/boodskap-ui
      register: dependencies_output

    - debug: msg="{{ dependencies_output }}"

    # - 
    #   name: This command will restart the node process.
    #   command: pm2 restart boodskap-platform-node.js
    #   args:
    #     chdir: /home/boodskapui/webapps/boodskap-ui
    #   register: command_output

    # - name: Restart output
    #   ansible.builtin.debug:
    #     var: command_output.stdout_lines


-
  hosts: nginx2_server
  tasks:
    - 
      name: Branch status.
      command: git branch
      args:
        chdir: /home/boodskapui/webapps/boodskap-ui
      register: branch_output

    - debug: msg="{{ branch_output }}"

    - 
      name: This command will restart the node process.
      command: pm2 restart boodskap-platform-node.js
      args:
        chdir: /home/boodskapui/webapps/boodskap-ui
      register: command_output

    - name: Restart output
      ansible.builtin.debug:
        var: command_output.stdout_lines