---
-
  hosts: haproxy1
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/BoodskapPlatform/boodskap-ui.git'
        clone: yes
        accept_newhostkey: yes
        dest: /home/ubuntu/build/v5-boodskap-ui/dev/boodskap-ui
        version: development
        force: yes
        single_branch: yes
      register: gitoutput

    - debug: msg="{{ gitoutput }}"
    
    - 
      name: Branch status.
      command: git branch
      args:
        chdir: /home/ubuntu/build/v5-boodskap-ui/dev/boodskap-ui
      register: branch_output

    - debug: msg="{{ branch_output }}"

    - 
      name: This command will install dependencies.
      command: npm install
      args:
        chdir: /home/ubuntu/build/v5-boodskap-ui/dev/boodskap-ui
      register: dependencies_output

    - debug: msg="{{ dependencies_output }}"

    - 
      name: Changing the version and Push the code.
      shell: "git stash"
      args:
        chdir: /home/ubuntu/build/v5-boodskap-ui/dev/boodskap-ui
      register: dependencies_output
    - debug: msg="{{ dependencies_output.stdout }}"

    -
      name: Docker build change mode to executable.
      shell: "chmod +x build.sh"
      args:
        chdir: /home/ubuntu/build/v5-boodskap-ui/dev/boodskap-ui
      register: change_buildscript_mode_output

    - debug: msg="{{ change_buildscript_mode_output.stdout }}"

    -
      name: Run docker build.
      shell: "./build.sh"
      args:
        chdir: /home/ubuntu/build/v5-boodskap-ui/dev/boodskap-ui
      register: run_build_script_output
    - debug: msg="{{ run_build_script_output.stdout }}"

    - name: Sleep for 10 seconds 
      wait_for:
        timeout: 10
      delegate_to: 127.0.0.1
    -
      name: Docker Push the latest image.
      shell: "sh push.sh"
      args:
        chdir: /home/ubuntu/build/v5-boodskap-ui/dev/boodskap-ui
      register: run_push_script_output
    - debug: msg="{{ run_push_script_output.stdout }}"

- hosts: v5dev
  tasks:
     -
       name: Deploy the container image.
       shell: "sh deploy.sh"
       args:
         chdir: /home/ubuntu/cluster/ui
       register: deploy_container_output
     - debug: msg="{{ deploy_container_output.stdout }}"